maxMin::[Int]->(Int,Int)
maxMin [x] = (x,x)
maxMin [x,y] | x<y = (x,y)
			 | otherwise = (y,x)
maxMin (x:y:z:xs) | x<y && x<z && y<z = maxMin(x:z:xs)
 				  | x<y && x<z && y>z = maxMin(x:y:xs)
 				  | x>y && x<z && y<z = maxMin(y:z:xs)
 				  | x<y && x>z && y>z = maxMin(z:y:xs)
				  | x>y && x>z && y>z = maxMin(z:x:xs)
				  | x>y && x>z && y<z = maxMin(y:x:xs)